name: Fluid
favicon: null
layout_spectrum: 0.440375539008528
typography_spectrum: 0.9155340597499162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.553936489392072
  lightness: 0.11876615905202925
  saturation: 0.24049680260941386
  rhythmicContrast: 0.5758662687148899
purpose: []
